repos:
    - repo: local
      hooks:
          - id: lint
            pass_filenames: false
            always_run: true
            name: lint
            entry: make lint
            language: system
            types: [python]
