name: CI

on: [push]

jobs:
    black:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Black Code Formatter
              uses: lgeiger/black-action@master
              with:
                  args: '--line-length=79 --check .'

    flake8:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Flake8 Code Linter
              uses: jonasrk/flake8-action@master
              with:
                  args: 'cd_dot_cz_price_search tests'

    pylint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: GitHub Action for pylint
              uses: jonasrk/GitHub-Action-for-pylint@master
              with:
                  args: 'pylint **/*.py'
